outcomesinsights/conceptql

- lib/conceptql/nodifier.rb
- lib/conceptql/operators/operator.rb
- lib/conceptql/operators/source_vocabulary_operator.rb
- lib/conceptql/operators/union.rb
This optimizes Union operators that union multiple instances of
the same SourceVocabularyOperator subclass with different values.
This only results in a 10% speed improvement with the test data
(246ms vs 271ms).  However, the speed up will probably be larger for
larger datasets.  The previous unoptimized approach is going to run
separate scans for each of the branches of the union, so speed for
large datasets should be O(n*m), where n is the number of branches
in the union and m is the size of the dataset.  With this approach,
speed should be O(m) for large datasets.
I think it should be possible to extend this approach to optimizing
unions of separate SourceVocaularyOperator subclasses.  That's a
more important optimization, since it should handle many more cases
than this optimization. …
> Optimize some Union operators

- lib/conceptql/operators/condition_occurrence_source_vocabulary_operator.rb
- lib/conceptql/operators/condition_occurrence_source_vocabulary_operator_union.rb
- lib/conceptql/operators/icd10.rb
- lib/conceptql/operators/icd9.rb
- lib/conceptql/operators/medcode.rb
- lib/conceptql/operators/operator.rb
- lib/conceptql/operators/source_vocabulary_operator.rb
- lib/conceptql/operators/union.rb
- lib/conceptql/query.rb
- spec/conceptql/operators/source_vocabulary_operator_spec.rb
Add optimization for union of ICD9, ICD10, Medcode operators
It's possible to optimize a union of these three cases to avoid
an SQL UNION ALL because they all join to the same table.
This adds a ConditionOccurrenceSourceVocabularyOperator subclass
for ICD9, ICD10, Medcode to subclass from.  This class can handle
unions of separate subclasses, by just ORing the conditions in
each of the subclasses.
To make things easier, this moves the scm.source_code =
condition_source_value from WHERE to JOIN ON, since that is the
same for each subclass. With this change the WHERE conditions for
multiple operators can just be joined with OR.
A ConditionOccurrenceSourceVocabularyOperatorUnion subclass is
added to handle a union of multiple
ConditionOccurrenceSourceVocabularyOperators.
Union#optimize will …
> Add optimization for union of ICD9, ICD10, Medcode operators

- lib/conceptql/operators/operator.rb
- lib/conceptql/query.rb
- spec/conceptql/query_spec.rb
Annotations will traverse the operator and for each operator,
give a count of the number of rows and the number of unique people
in the query.
The implementation is fairly simple, starting with the root operator,
recursing into all upstreams, and running a count query for each
operator.
> Add support for annotations to queries

- lib/conceptql/operators/binary_operator_operator.rb
- lib/conceptql/operators/operator.rb
- spec/conceptql/query_spec.rb
Add private annotate_values method that operator subclasses can
override for the annotation of their arguments.
> Handle annotations for binary operators

- lib/conceptql/annotate_grapher.rb
- lib/conceptql/operators/operator.rb
- spec/conceptql/query_spec.rb
This takes output from Query#annotate and builds a Graphviz diagram,
without having access to a database.  This will eventually allow
the removal of graphing code from operators, Graph, GraphNodifier,
and potentially other places.
No tests yet as currently the only output is PDF.
Also, handle annotations for operators using hashes.
> Add ConceptQL::AnnotateGrapher

- test/db.rb
- test/db_setup.rb
- test/operators/person_filter_test.rb
There is no implicit casting of literals to numbers or varchar,
so this adds explicit casts to the type of the column. It also
allows rake test_db_setup to be run multiple times without
inserting duplicate data.
Impala can't handle inserting all test data in a single query,
so add a :slice option to Dataset#import.  A recent change I
committed to sequel-impala allows Dataset#import on Impala to
insert multiple rows at once, which speeds up the import
process by multiple orders of magnitude.
This also fixes the one test failure on PostgreSQL, which was
because I didn't take into account the duplicate data in
test_conceptql.
> Allow rake test_db_setup to work on Impala

- lib/conceptql.rb
- lib/conceptql/database.rb
- test/helper.rb
This makes it simpler to create queries for the same database,
without passing that database as an argument to every call to
Query.new.
> Add ConceptQL::Database

- lib/conceptql/knitter.rb
- lib/conceptql/operators/operator.rb
- test/fake_annotater_test.rb
- test/knitter/conceptql.md.cql
- test/knitter/conceptql.md.expect
- test/knitter/fake.md.cql
- test/knitter/fake.md.expect
- test/knitter/no_conceptql.md.cql
- test/knitter/title.md.cql
- test/knitter/title.md.expect
- test/knitter_test.rb
- test/operators/date_range_test.rb
- test/operators/except_test.rb
- test/operators/intersect_test.rb
This adds tests for FakeAnnotate and Knitter, as well as more tests for Query#annotate to make sure it works with additional operators, such as operators with options and binary operators.
Both FakeAnnotate and Knitter have tests with 100% line coverage, except for 2 methods in Knitter which are not called and could possibly be removed
A couple minor lib changes are included. One removes a debugging line left in, and the other uses Knitter#lib inside Knitter.
> Add more tests

- lib/conceptql/cli.rb
It's not safe to write to any file in a known world-writable
location, as an attacker can symlink it to any other file that
you can write to.
One secure way to write to a file in /tmp is to use a mkstemp
or similar function, but I think a simpler solution here is just
to write the file to current directory.  If that isn't advisable,
then metadata should require a file name argument for where
to write the file.
> Avoid symlink attack in bin/conceptql metadata

- lib/conceptql/operators/except.rb
- lib/conceptql/operators/occurrence.rb
- lib/conceptql/operators/one_in_two_out.rb
- lib/conceptql/operators/operator.rb
- lib/conceptql/scope.rb
- test/knitter/conceptql.md.expect
- test/knitter/except.md.expect
- test/knitter/many.md.expect
- test/knitter/union.md.expect
- test/knitter_test.rb
- test/operators/recall_test.rb
This fixes the use of recall with an occurrence operator.  I first tried just using WITH RECURSIVE, which did work on PostgreSQL, but didn't work on Impala.  So I developed a fix that works on both, having Occurrence and OneInTwoOut add the CTEs to the Scope, and have the Scope add them after the other CTEs.
I ran into a couple issues in the Impala tests.  First, the Except operator didn't work on Impala after the CTE change, because sequel-impala's EXCEPT emulation needed to determine the columns.  This is fixed by setting the columns for the datasets before calling Dataset#except.
There was also some bad Impala-related code in Operator#cast_date, which I removed.  It looks like the code had been moved to Operator#assemble_date.
I added freezing of some Operator constants which shouldn't …
> Fixes for CTEs and Impala

- lib/conceptql/operators/intersect.rb
This is a similar to the change made to the Except operator.
> Fix queries to get the columns on Impala in the Intersect operator

- lib/conceptql/operators/operator.rb
- lib/conceptql/scope.rb
- test/operators/recall_test.rb
Fixes an infinite loop in sort_ctes if an invalid recall operator
is used (one with no matching label).
When annotating, skip all annotations if the scope is not valid,
as otherwise it will attempt to execute invalid SQL.
> Check that all recall operators in the scope are valid before executing query

- lib/conceptql/operators/occurrence.rb
- lib/conceptql/operators/one_in_two_out.rb
- lib/conceptql/operators/operator.rb
- lib/conceptql/scope.rb
- test/operators/recall_test.rb
If an operator uses extra_ctes and is a recall label, it needs to
be added as a CTE before uses of the recall operator.
Currently, only the one_in_two_out operator and the occurrence
operator use extra ctes, so this just adds a notation in both
classes.
> Handle operators that use extra_ctes that have recall labels

- lib/conceptql/operators/operator.rb
This makes it a lot simpler to read the output, and translates
nicer into JSON.
The next step after this is fixing the tests.
> Only include upstream operator names in error data

- test/helper.rb
If checking the JSON, take actual results data structure, convert
it to JSON and back, and compare the result to the parsed version
of the saved expected output.
This fixes failures due to differences in JSON formatting.
> Less fragile JSON checking

- lib/conceptql/scope.rb
In Sequel 5, datasets are frozen, so you can't modify the singleton
class of a dataset.  You can use with_extend instead, which returns
a modified copy. The with_extend block is passed is to Module.new,
and the resulting module extends the copy of the dataset.
> Make CONCEPTQL_CHECK_COLUMNS work on Sequel 5

- lib/conceptql.rb
- lib/conceptql/operators/co_reported.rb
- lib/conceptql/operators/occurrence.rb
- lib/conceptql/operators/operator.rb
- lib/conceptql/scope.rb
This makes CTEs use unique names created with the process id, an
incrementing counter, and a random number.  This should make it
very unlikely there are collisions even when running simultaneously
on different hosts.
This also lays the groundwork for the CONCEPTQL_FORCE_TEMP_TABLES
and DOCKER_SCRATCH_DATABASE environment variables, but those won't
work correctly yet, I still need to add support so that
Dataset#each will strip off any ctes and create temp tables
for them, and clean up the temp tables after yielding all rows.
> Use unique CTE names

- lib/conceptql/operators/filter.rb
- lib/conceptql/operators/operator.rb
This is a work-in-progress pull request, not currently ready for merging.
I added support for the match operator locally, but it doesn't look like we have tests for that operator, so I haven't committed it.
I tried to add support for the place_of_service_code operator, but it doesn't appear to work there, maybe because it tried to select columns from the joined table (RHS) instead of the just the main table (LHS).
Please let me know what operators are the most important in terms of adding support for this, so I can work on those first.
> Add Operator#semi_or_inner_join, and support in filter operator

- lib/conceptql/scope.rb
Only one map should be done, not two maps.  Fixes infinite recursion
on the mock impala adapter.
> Remove duplicate call to recursive_extract_cte_expr (Fixes #188)

- lib/conceptql/operators/concurrent_within.rb
- lib/conceptql/window/table.rb
- test/helper.rb
Impala can't handle (col1, col2) IN (subquery), and Sequel's
emulation cannot handle in this particular case.  Switch to
EXISTS (subquery WHERE l.col1 = r.col1 AND l.col2 = r.col2),
which can work in this particular case.
In a somewhat similar case, Sequel's select_remove extension
cannot handle cases where running the query to get the columns
doesn't work (and it doesn't in this case).  Do some manual
dataset introspection that works for many ConceptQL cases due
to the extensive use of SELECT * FROM (SELECT * FROM (SELECT * FROM,
and only fallback to the use of the select_remove if that
introspection doesn't work.
> Fix concurrent_within operator on Impala

- lib/conceptql/scope.rb
This uses Sequel::ASTTransformer to process the WHERE clause and
extract any CTEs from datasets in the WHERE clause.
> Extract CTEs in WHERE clauses

- lib/conceptql/rdbms/impala.rb
- lib/conceptql/rdbms/postgres.rb
- lib/conceptql/scope.rb
b67e839e1ee1ca5aa039f93c9d0622f28f35a434 added the use of :sort_by
option if the CONCEPTQL_SORT_TEMP_TABLES env variable was set.  It
had create_options take a scope argument, but it did not pass the
ConceptQL::Scope object in, it passed a Sequel::Dataset instance in,
and the dataset it passed in was the dataset that was retrieving the
results, not the dataset that was used to build the temporary table.
This is because create_options(self) was used in a define_method
block inside one of the scope methods.  Fix this to actually pass
the scope in, by storing the scope in a local variable.
That change exposed another bug, which is that checking against the
scope's query_columns is not correct in all cases.  At least for the
failing query in question, which uses a VALUES query, we should use …
> Fix breakage caused CONCEPTQL_SORT_TEMP_TABLES=true

- lib/conceptql/operators/operator.rb
- lib/conceptql/scope.rb
- test/lib/conceptql/operators/icd9_test.rb
Also, setup the args CTE on impala to not use a temp table.
> Allow use of :no_temp_table Dataset#with option for not extracting CTE to temp table

- Gemfile
- conceptql.gemspec
The sequelizer dependency is temporarily pointing at https://github.com/mattschultz/sequelizer/tree/eyeleteer-rails6 until it can be merged into the upstream.
> Bump thor and activesupport gems for Rails 6.1
